In [11]:
import numpy as np
import pandas as pd

data = pd.DataFrame(
    np.transpose(
        [
            [34, 37, 44, 27, 19, 39, 74, 44, 27, 61, 12, 65, 69, 22, 14, 21],
            [18, 33, 47, 24, 14, 38, 66, 41, 36, 72, 15, 62, 63, 31, 12, 18],
            [32, 43, 36, 12, 21, 51, 75, 33, 23, 60, 24, 68, 85, 18, 13, 14],
            [13, 31, 55, 29, 15, 62, 74, 43, 28, 73, 8, 59, 54, 32, 19, 20],
            [8, 28, 34, 24, 17, 68, 75, 34, 25, 70, 16, 56, 72, 31, 14, 11],
            [9, 34, 43, 25, 18, 68, 84, 25, 32, 76, 14, 69, 64, 27, 11, 18],
            [15, 20, 28, 18, 19, 65, 82, 34, 29, 89, 11, 47, 74, 18, 22, 17],
            [18, 14, 40, 25, 21, 60, 70, 15, 37, 80, 15, 65, 68, 21, 25, 9],
            [19, 18, 41, 26, 19, 58, 64, 18, 38, 78, 15, 65, 72, 20, 20, 11],
            [13, 29, 49, 31, 16, 61, 73, 36, 29, 69, 13, 63, 58, 18, 20, 25],
            [17, 34, 43, 29, 14, 62, 64, 26, 26, 71, 26, 78, 64, 21, 18, 12],
            [13, 22, 43, 16, 11, 70, 68, 46, 35, 57, 30, 71, 57, 19, 22, 20],
            [16, 18, 56, 13, 27, 67, 61, 43, 20, 63, 14, 43, 67, 34, 41, 23],
            [15, 21, 66, 21, 19, 50, 62, 50, 24, 68, 14, 40, 58, 31, 36, 26],
            [19, 17, 70, 12, 28, 53, 72, 39, 22, 71, 11, 40, 67, 25, 41, 17],
        ]
    ),
    columns=[
        "CD1",
        "CD2",
        "CD3",
        "RD1",
        "RD2",
        "RD3",
        "TB1",
        "TB2",
        "TB3",
        "MS1",
        "MS2",
        "MS3",
        "MT1",
        "MT2",
        "MT3",
    ],
)


def ejemplo_base(df):

    matrix = df.transpose().values
    grand_total = np.sum(matrix)
    correspondence_matrix = np.divide(matrix, grand_total)
    row_totals = np.sum(correspondence_matrix, axis=1)
    col_totals = np.sum(correspondence_matrix, axis=0)
    independence_model = np.outer(row_totals, col_totals)

    norm_correspondence_matrix = np.divide(correspondence_matrix, row_totals[:, None])
    distances = np.zeros(
        (correspondence_matrix.shape[0], correspondence_matrix.shape[0])
    )
    norm_col_totals = np.sum(norm_correspondence_matrix, axis=0)
    for row in range(correspondence_matrix.shape[0]):
        distances[row] = np.sqrt(
            np.sum(
                np.square(norm_correspondence_matrix - norm_correspondence_matrix[row])
                / col_totals,
                axis=1,
            )
        )
    std_residuals = np.divide(
        (correspondence_matrix - independence_model), np.sqrt(independence_model)
    )
    u, s, vh = np.linalg.svd(std_residuals, full_matrices=False)
    deltaR = np.diag(np.divide(1.0, np.sqrt(row_totals)))
    rowScores = np.dot(np.dot(deltaR, u), np.diag(s))

    xy = pd.DataFrame(
        data=[l[0:2] for l in rowScores], columns=["X", "Y"], index=df.columns
    )

    return xy


ejemplo_base(data)

(15, 15)

In [12]:
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/USArrests.csv')

    Murder  Assault  UrbanPop  Rape           State
0     13.2      236        58  21.2         Alabama
1     10.0      263        48  44.5          Alaska
2      8.1      294        80  31.0         Arizona
3      8.8      190        50  19.5        Arkansas
4      9.0      276        91  40.6      California
5      7.9      204        78  38.7        Colorado
6      3.3      110        77  11.1     Connecticut
7      5.9      238        72  15.8        Delaware
8     15.4      335        80  31.9         Florida
9     17.4      211        60  25.8         Georgia
10     5.3       46        83  20.2          Hawaii
11     2.6      120        54  14.2           Idaho
12    10.4      249        83  24.0        Illinois
13     7.2      113        65  21.0         Indiana
14     2.2       56        57  11.3            Iowa
15     6.0      115        66  18.0          Kansas
16     9.7      109        52  16.3        Kentucky
17    15.4      249        66  22.2       Louisiana
18     2.1       83        51   7.8           Maine
19    11.3      300        67  27.8        Maryland
20     4.4      149        85  16.3   Massachusetts
21    12.1      255        74  35.1        Michigan
22     2.7       72        66  14.9       Minnesota
23    16.1      259        44  17.1     Mississippi
24     9.0      178        70  28.2        Missouri
25     6.0      109        53  16.4         Montana
26     4.3      102        62  16.5        Nebraska
27    12.2      252        81  46.0          Nevada
28     2.1       57        56   9.5   New Hampshire
29     7.4      159        89  18.8      New Jersey
30    11.4      285        70  32.1      New Mexico
31    11.1      254        86  26.1        New York
32    13.0      337        45  16.1  North Carolina
33     0.8       45        44   7.3    North Dakota
34     7.3      120        75  21.4            Ohio
35     6.6      151        68  20.0        Oklahoma
36     4.9      159        67  29.3          Oregon
37     6.3      106        72  14.9    Pennsylvania
38     3.4      174        87   8.3    Rhode Island
39    14.4      279        48  22.5  South Carolina
40     3.8       86        45  12.8    South Dakota
41    13.2      188        59  26.9       Tennessee
42    12.7      201        80  25.5           Texas
43     3.2      120        80  22.9            Utah
44     2.2       48        32  11.2         Vermont
45     8.5      156        63  20.7        Virginia
46     4.0      145        73  26.2      Washington
47     5.7       81        39   9.3   West Virginia
48     2.6       53        66  10.8       Wisconsin
49     6.8      161        60  15.6         Wyoming